/**
 * Curated JS / React interview-style problems for /practice.
 * `companies` supports sidebar filtering (hasSome overlap on the API).
 */
export type InterviewChallengeSeed = {
  title: string;
  description: string;
  difficulty: string;
  practiceLanguage: string;
  companies: string[];
  estimatedTime: string;
  inputFormat: string;
  outputFormat: string;
  constraints: string;
  sampleInput: string;
  sampleOutput: string;
};

export const interviewPracticeChallenges: InterviewChallengeSeed[] = [
  {
    title: 'Anagram Checker',
    description: 'Determine if two strings are anagrams of each other, ignoring case and extra spaces.',
    difficulty: 'Easy',
    practiceLanguage: 'JavaScript',
    companies: ['Google', 'Amazon'],
    estimatedTime: '5 mins',
    inputFormat: 'Two lines: string a and string b.',
    outputFormat: 'Print YES or NO.',
    constraints: '1 <= length <= 5000',
    sampleInput: 'listen\nsilent',
    sampleOutput: 'YES',
  },
  {
    title: 'Power of Four',
    description: 'Return true if n is a power of 4, false otherwise (integer n, can be negative handling optional).',
    difficulty: 'Easy',
    practiceLanguage: 'JavaScript',
    companies: ['Google', 'Meta', 'Microsoft', 'Amazon'],
    estimatedTime: '10 mins',
    inputFormat: 'One integer n.',
    outputFormat: 'Print true or false.',
    constraints: '-2^31 <= n <= 2^31-1',
    sampleInput: '16',
    sampleOutput: 'true',
  },
  {
    title: 'Flatten Nested Array',
    description: 'Create a function that takes a nested array of arbitrary depth and returns a flattened array.',
    difficulty: 'Easy',
    practiceLanguage: 'JavaScript',
    companies: ['Microsoft', 'Amazon', 'Accenture', 'Capgemini'],
    estimatedTime: '10 mins',
    inputFormat: 'JSON array of nested numbers.',
    outputFormat: 'JSON array of numbers in flat order.',
    constraints: 'Depth <= 20',
    sampleInput: '[1,[2,[3]],4]',
    sampleOutput: '[1,2,3,4]',
  },
  {
    title: 'Find Smallest Number',
    description: 'Given an array of integers, return the smallest value (handle empty array as specified).',
    difficulty: 'Easy',
    practiceLanguage: 'JavaScript',
    companies: ['TCS', 'Infosys', 'Wipro', 'Amazon'],
    estimatedTime: '5 mins',
    inputFormat: 'First line: n. Second line: n integers.',
    outputFormat: 'Print the minimum integer.',
    constraints: '1 <= n <= 10^5',
    sampleInput: '5\n3 1 4 1 5',
    sampleOutput: '1',
  },
  {
    title: 'Voting Eligibility',
    description: 'Given age, print whether the person can vote (assume threshold 18).',
    difficulty: 'Easy',
    practiceLanguage: 'JavaScript',
    companies: ['TCS', 'Infosys', 'Wipro'],
    estimatedTime: '5 mins',
    inputFormat: 'One integer age.',
    outputFormat: 'Print ELIGIBLE or NOT ELIGIBLE.',
    constraints: '0 <= age <= 120',
    sampleInput: '21',
    sampleOutput: 'ELIGIBLE',
  },
  {
    title: 'Debounce Function',
    description: 'Implement debounce(fn, delay) that delays invoking fn until delay ms have passed since the last call.',
    difficulty: 'Medium',
    practiceLanguage: 'JavaScript',
    companies: ['Meta', 'Google', 'Uber', 'Atlassian'],
    estimatedTime: '20 mins',
    inputFormat: 'N/A — implement the utility; tests call your exported function.',
    outputFormat: 'N/A',
    constraints: 'delay >= 0',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Deep Clone (JSON-safe)',
    description: 'Implement deepClone(value) for plain objects, arrays, strings, numbers, booleans, and null.',
    difficulty: 'Medium',
    practiceLanguage: 'JavaScript',
    companies: ['Amazon', 'Adobe', 'Salesforce'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'No functions, dates, or circular refs in tests',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Promise.allSettled Polyfill',
    description: 'Write promiseAllSettled(iterable) matching Promise.allSettled semantics.',
    difficulty: 'Medium',
    practiceLanguage: 'JavaScript',
    companies: ['Meta', 'Netflix', 'Airbnb'],
    estimatedTime: '20 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Handle mixed fulfill/reject',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'LRU Cache',
    description: 'Implement an LRU cache with get and put operating in average O(1) time.',
    difficulty: 'Hard',
    practiceLanguage: 'JavaScript',
    companies: ['Google', 'Amazon', 'Microsoft', 'Uber'],
    estimatedTime: '35 mins',
    inputFormat: 'N/A — class API used by tests',
    outputFormat: 'N/A',
    constraints: 'Capacity >= 1',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Curry Implementation',
    description: 'Implement curry(fn) so curried functions accept arguments until arity is satisfied.',
    difficulty: 'Hard',
    practiceLanguage: 'JavaScript',
    companies: ['Meta', 'Stripe', 'Airbnb'],
    estimatedTime: '30 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Fixed arity functions in tests',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Array to Zigzag String Converter',
    description: 'Rearrange characters of a string in a zigzag pattern with a given number of rows (classic LC-style).',
    difficulty: 'Medium',
    practiceLanguage: 'JavaScript',
    companies: ['Amazon', 'Google', 'Meta'],
    estimatedTime: '20 mins',
    inputFormat: 'Line 1: string s. Line 2: integer numRows.',
    outputFormat: 'Print zigzag concatenation.',
    constraints: '1 <= numRows <= s.length <= 1000',
    sampleInput: 'PAYPALISHIRING\n3',
    sampleOutput: 'PAHNAPLSIIGYIR',
  },
  {
    title: 'Throttle Function',
    description: 'Implement throttle(fn, wait) so fn runs at most once per wait ms while events fire.',
    difficulty: 'Medium',
    practiceLanguage: 'JavaScript',
    companies: ['Google', 'Slack', 'Zoom'],
    estimatedTime: '20 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'wait > 0',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Memoize With Resolver',
    description: 'Implement memoize(fn, resolver?) to cache results; resolver maps args to cache key.',
    difficulty: 'Medium',
    practiceLanguage: 'JavaScript',
    companies: ['Meta', 'Amazon'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Pure fn in tests',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Event Emitter',
    description: 'Implement on, off, and emit for a simple pub/sub object.',
    difficulty: 'Medium',
    practiceLanguage: 'JavaScript',
    companies: ['Microsoft', 'Atlassian', 'BrowserStack'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Event names are strings',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Compose Pipe',
    description: 'Implement compose(...fns) and pipe(...fns) for left-to-right and right-to-left composition.',
    difficulty: 'Medium',
    practiceLanguage: 'JavaScript',
    companies: ['Airbnb', 'Shopify'],
    estimatedTime: '15 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Unary functions in tests',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Binary Search',
    description: 'Return index of target in sorted array, or -1 if missing.',
    difficulty: 'Easy',
    practiceLanguage: 'JavaScript',
    companies: ['Amazon', 'Google', 'Apple'],
    estimatedTime: '15 mins',
    inputFormat: 'Line 1: sorted integers space-separated. Line 2: target.',
    outputFormat: 'Print index or -1.',
    constraints: 'Array length <= 10^5',
    sampleInput: '1 3 5 7 9\n5',
    sampleOutput: '2',
  },
  {
    title: 'Valid Parentheses',
    description: 'Determine if a string of brackets is valid.',
    difficulty: 'Easy',
    practiceLanguage: 'JavaScript',
    companies: ['Amazon', 'Bloomberg', 'Adobe'],
    estimatedTime: '15 mins',
    inputFormat: 'One string of ()[]{}',
    outputFormat: 'Print VALID or INVALID.',
    constraints: 'Length <= 10^4',
    sampleInput: '()[]{}',
    sampleOutput: 'VALID',
  },
  {
    title: 'Contact Form',
    description: 'Build a controlled contact form with name, email, message, validation, and submit handler.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Meta', 'Google', 'Paytm'],
    estimatedTime: '10 mins',
    inputFormat: 'N/A — React component',
    outputFormat: 'N/A',
    constraints: 'Client-side validation for email format',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Copy to Clipboard',
    description: 'Create a button that copies given text to the clipboard with user feedback.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Oracle', 'Paytm', 'LinkedIn'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Graceful fallback if clipboard API unavailable',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Holy Grail Layout',
    description: 'Implement a responsive holy grail layout with header, footer, and three columns using CSS/React structure.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Amazon', 'Google', 'Flipkart'],
    estimatedTime: '20 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Mobile: stack columns',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Accordion',
    description: 'Build an accordion: only one section open at a time; smooth expand/collapse.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Meta', 'Airbnb', 'Zomato'],
    estimatedTime: '20 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Data-driven items from props',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Password Strength',
    description: 'Indicator for password strength based on length, mixed case, digits, and symbols.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Google', 'Microsoft', 'Auth0'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Controlled input',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Auto Save Text',
    description: 'Textarea that auto-saves draft to localStorage with debounced updates and restore on load.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Atlassian', 'Amazon', 'Zomato'],
    estimatedTime: '15 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Namespace key by route or id',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Infinite Scroll List',
    description: 'Render a list that loads more items as the user scrolls near the bottom.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Meta', 'Pinterest', 'Instagram'],
    estimatedTime: '30 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Use IntersectionObserver or scroll events',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Modal Dialog',
    description: 'Accessible modal with focus trap, ESC to close, and backdrop click handling.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Microsoft', 'Salesforce', 'Adobe'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'aria-modal and labelledby',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Data Table With Sort',
    description: 'Table with sortable columns and basic pagination controls.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Amazon', 'Uber', 'Snowflake'],
    estimatedTime: '35 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Stable sort on one column at a time',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Searchable Dropdown',
    description: 'Combobox that filters options as the user types and supports keyboard navigation.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Google', 'Slack', 'Notion'],
    estimatedTime: '35 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Large option lists — avoid filtering lag',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Tabs Component',
    description: 'Accessible tabs with keyboard support (arrow keys) and ARIA roles.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Meta', 'Atlassian', 'GitHub'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Controlled and uncontrolled modes optional',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Star Rating',
    description: 'Interactive star rating with half-star optional; emits value on change.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Zomato', 'Swiggy', 'Uber'],
    estimatedTime: '20 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: '5 stars default',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Todo List (CRUD)',
    description: 'Classic todo app: add, toggle complete, delete, filter all/active/completed.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Meta', 'Amazon', 'Netflix'],
    estimatedTime: '30 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Lift state or useReducer',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Image Carousel',
    description: 'Carousel with prev/next, dots, and optional autoplay pause on hover.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Instagram', 'Snap', 'Meta'],
    estimatedTime: '30 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Loop edges or clamp — document choice',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Form Multi-Step Wizard',
    description: 'Multi-step form with validation per step and review screen before submit.',
    difficulty: 'Hard',
    practiceLanguage: 'React.js',
    companies: ['Salesforce', 'Workday', 'SAP'],
    estimatedTime: '45 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Cannot advance with invalid step',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Virtualized List',
    description: 'Render only visible rows for a long list (fixed row height).',
    difficulty: 'Hard',
    practiceLanguage: 'React.js',
    companies: ['Google', 'Meta', 'Twitter'],
    estimatedTime: '40 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: '10k+ items',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'useFetch Hook',
    description: 'Custom hook useFetch(url) returning data, loading, error, and refetch.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Airbnb', 'Vercel', 'Netlify'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Abort on unmount or URL change',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Theme Toggle (Context)',
    description: 'Light/dark theme using React context and persisted preference.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['GitHub', 'Vercel', 'Linear'],
    estimatedTime: '20 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Respect system preference as default',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Drag and Drop List',
    description: 'Reorder list items via drag-and-drop with visual feedback.',
    difficulty: 'Hard',
    practiceLanguage: 'React.js',
    companies: ['Atlassian', 'Notion', 'Trello'],
    estimatedTime: '40 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Pointer events or HTML5 DnD',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'File Drop Zone',
    description: 'Upload area accepting drag-drop and click; show file names and sizes.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Dropbox', 'Google Drive', 'Box'],
    estimatedTime: '25 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Validate max size client-side',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Countdown Timer',
    description: 'Timer component with start/pause/reset and MM:SS display.',
    difficulty: 'Easy',
    practiceLanguage: 'React.js',
    companies: ['Uber', 'Doordash', 'Instacart'],
    estimatedTime: '20 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'useRef for interval cleanup',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'OTP Input',
    description: 'Six-digit OTP boxes with auto-advance, paste support, and backspace navigation.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Paytm', 'PhonePe', 'Google'],
    estimatedTime: '30 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Numeric only',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Chart Wrapper',
    description: 'Wrap a chart library or SVG mini-chart showing trend from props data.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Databricks', 'Snowflake', 'Tableau'],
    estimatedTime: '30 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Responsive container',
    sampleInput: '',
    sampleOutput: '',
  },
  {
    title: 'Notification Toast System',
    description: 'Global toast provider: success/error/info with auto-dismiss and stacking.',
    difficulty: 'Medium',
    practiceLanguage: 'React.js',
    companies: ['Stripe', 'Vercel', 'Shopify'],
    estimatedTime: '30 mins',
    inputFormat: 'N/A',
    outputFormat: 'N/A',
    constraints: 'Portal to document body',
    sampleInput: '',
    sampleOutput: '',
  },
];
